### ISSUE TITLE
Maths Part III students

### ISSUE THREAD

**Issue by petermr** [ContentMine/site#101]
Construct ContentMine-useful summer projects for mathematics students with the goals of:

* getting specific problems solved
* linking into an important community (undergraduate maths)
* getting ourselves known to students and staff

Attend launch meeting in 2nd week November

[NB @Treblesteph has already been involved last year but the whole program folded. If there is a really good student we could consider funding them from Content Mine (8 weeks @250 GBP / week)

**Comment by Blahah** [comment]
this ship has sailed I think
