### ISSUE TITLE
Blog issues - dead links for some posts

### ISSUE THREAD

**Issue by GrahamSteel** [ContentMine/site#158]

**Comment by GrahamSteel** [comment]
e.g. http://contentmine.org/api/catalogue/378812d761564a828db7750780e7f329

**Comment by markmacgillivray** [comment]
This is a link to an API document, not a blog post. Are there any dead links on the actual blog that need fixed?

**Comment by GrahamSteel** [comment]
http://contentmine.org/blog/Chicago_workshop & http://contentmine.org/blog/ami

**Comment by markmacgillivray** [comment]
Ah, they are not actually failing, just the authors had not made them public and as you are not logged in you get the 404. I have changed the AMI one, you should be able to view it now, although it also seems to be unfinished. However for the chicago one there is an actual error in trying to save the settings of the post. I will look into that.

**Comment by GrahamSteel** [comment]
Cool, thanks.
