### ISSUE TITLE
Book Digital Open Science meetings

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/site#171]
Makespace, Saturday afternoons monthly March onwards

**Comment by jcmolloy** [comment]
Have booked under title 'Hack the Lab' in an on-going attempt not to duplicate effort across my jobs! 
http://www.meetup.com/Makespace/events/220734355/

Billed as being for people working on scientific hardware, but ContentMine can start a software contingent....

**Comment by petermr** [comment]
Thanks Jenny - is this in the communal diary ?

On Tue, Feb 3, 2015 at 10:27 AM, Jenny Molloy <notifications@github.com>
wrote:

> Makespace, Saturday afternoons monthly March onwards
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ContentMine/site/issues/171>.
>



-- 
Peter Murray-Rust
Reader in Molecular Informatics
Unilever Centre, Dep. Of Chemistry
University of Cambridge
CB2 1EW, UK
+44-1223-763069

**Comment by jcmolloy** [comment]
It will be when we get the communal calendar set up - @grahamsteel will
look into this now we have the WordPress running.
In the meantime we can set up a gcal - Graham do you think you could hunt
around for dates that might need to be added? I have a bunch of issues
called 'find out who is going to' which would be a good source of events to
put in the calendar.

Jenny

**Comment by GrahamSteel** [comment]
So Wordpress have a plug-in for that https://wordpress.org/plugins/the-events-calendar/installation/

Whilst I'm seeing a Widgets page on WP, can't see one for plug-in's.

**Comment by GrahamSteel** [comment]
@sciencebase @McDawg If you're on http://wordpress.com  you can't add arbitrary plugins. Self-hosted it's down the menu on the left below Appearance

**Comment by jcmolloy** [comment]
OK - well let's at least get a google calendar then we can give everyone
the iCal link or similar and you can probably display it via an iframe on
WordPress.
