### ISSUE TITLE
Social media and filming during workshop

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/site#178]
Probably not livestreaming, but see what you think. We should aim for some short, good quality sound bites from attendees and maybe some good quality filming of the sessions for the online training resources. 

May be able to ask Wellcome for AV kit if that would help.

**Comment by GrahamSteel** [comment]
Agree on not streaming, better to focus on the other areas flagged up. Can film via laptop/phone/video camera. If Wellcome can provide any AV kit that would be awesome.

**Comment by jcmolloy** [comment]
Cool - have you been copied into any emails to Robery Kiley? i.e. do you
have his email address?
If so, probably best if you contact him to ask about AV equipment that we
could borrow for the day as you'll know best what is needed.
If not, I'll forward to you now anyway.

**Comment by GrahamSteel** [comment]
Not been copied into emails with Robert. I trust he is still at r.kiley@wellcome.ac.uk, Will contact him in this regard.

**Comment by jcmolloy** [comment]
Yes - I was avoiding posting the address on here but it seems it's public
on the web in many places anyhow!

**Comment by GrahamSteel** [comment]
This one has been resolved via email.
