### ISSUE TITLE
Set up repository for workshop resources

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/site#179]

**Comment by Treblesteph** [comment]
Is this in addition to the following?
https://github.com/ContentMine/WellcomeTrust-April2015
https://github.com/ContentMine/workshops

**Comment by jcmolloy** [comment]
'Set up' should really have been 'check and take responsibility for
ensuring everything is linked and ready on the day'.
So no :)

**Comment by Treblesteph** [comment]
Ah ok great :)
