### ISSUE TITLE
Organise venue and timings

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/site#183]
Attending from ContentMine:
@petermr @markmacgillivray @rossmounce @GrahamSteel 
Could you comment on the schedule below? I will share with UKCC early next week.

Schedule:

09:30 - Introductions
10:00 - Overview of ContentMine
10:30 - Discussion: why might content mining clinical trials be useful?
11:00 - Tea/coffee break
11:15 - Discussion: current tools and what is needed
12:00 - Discussion: imagining the clinical trials mining pipeline
12:30 - Lunch
13:30 - Demo and introduction to software
14:30 - Technical session 1 (hands-on content mining)
15:30 - Tea/coffee break
15:45 - Technical session 2 (hands-on content mining)
17:00 - Event close

UKCC will provide tea/coffee facilities. @GrahamSteel is organising lunch catering. We may need additional extension cables and a hotspot as the wifi apparently isn't used to large groups being very active on it, although it should be OK.

**Comment by jcmolloy** [comment]
@GrahamSteel did you find any catering options in Oxford? Cochrane suggested Mortons. We have a budget of around £200 for 20 people. See what you can do :)

**Comment by GrahamSteel** [comment]
Morton's is probably one of the easiest options. Can be ordered on the day or in advance. Free delivery given the fact we are catering for 15-20 people.

I'll pack the same kit that worked very well at #opendataday

**Comment by jcmolloy** [comment]
Great - let's order in advance with the caveat that we don't have dietary
requirement info yet so may have to amend slightly, but if we order plenty
of vegetarian regardless we're at least covered on that front.
