### ISSUE TITLE
What is content mining? [Can't tell from site]

### ISSUE THREAD

**Issue by rossmounce** [ContentMine/site#233]
Might be useful to link to this wiki entry (https://github.com/petermr/contentMine/wiki/ContentMining) where 'content mining' is mentioned on contentmine.org e.g. on the homepage http://contentmine.org/. I'm sure many won't be 100% sure what content mining is when they reach the site!

**Comment by GrahamSteel** [comment]
One for myself and @skasberger to re-open once we start work on the linked up CM url's later this month.
