### ISSUE TITLE
Post info on Swiss copyright case to Discourse

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/site#262]
CO to follow up on Swiss case and post on Discourse then distribute link to colleagues. Discourse link: http://discuss.contentmine.org/t/legal-aspects-copyright/119

**Comment by CharlesOppenheim** [comment]
Completed
Professor Charles Oppenheim
----Original message----
From : notifications@github.com
Date : 26/08/2015 - 12:00 (BST)
To : old_site@noreply.github.com
Cc : c.oppenheim@btinternet.com
Subject : [old_site] Post info on Swiss copyright case to Discourse (#262)
CO to follow up on Swiss case and post on Discourse then distribute link to colleagues. Discourse link: http://discuss.contentmine.org/t/legal-aspects-copyright/119
