### ISSUE TITLE
Coding page for Get Involved

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/site#274]
Links to:
- [ ] Scraper contribution tutorials on github
- [ ] Reciprocal links to software page on githu
- [ ] Report a bug/issue
- [ ] Refactor code
- [ ] Feature requests
- [ ] Upload/describe your CM demos/examples
- [ ] ? Contribute style sheets for norma

![websiteplan](https://cloud.githubusercontent.com/assets/883789/9832400/9f028478-5971-11e5-8a7d-a0e0df588490.jpg)
b/website

**Comment by skasberger** [comment]
add text, remove cmunity content, offer easy going things to do and direct to our channels of interaction.
