### ISSUE TITLE
1000 word case study for UfW's WILDLABS.NET on IUCN Red List mining

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/site#284]
WILDLABS.NET is an online community for people using technology to tackle different conservation challenges, we have been invited to write a case study for them.

More info:
[WILDLABSNETContentGuidelines.pdf](https://github.com/ContentMine/old_site/files/18398/WILDLABSNETContentGuidelines.pdf)
[WILDLABSNET_Flyer_A4.pdf](https://github.com/ContentMine/old_site/files/18399/WILDLABSNET_Flyer_A4.pdf)

"As we bring the community online, we’re also interested in hearing about projects that are using technology to tackle different conservation challenges as well as profiling a range of technologies under development or in use. To this end, we are also inviting submissions of case studies and reviews of technology, as well as thought pieces about the where and how technology might further conservation’s efforts to address the significant issues facing our planet.  

Would you be interested in contributing a piece about the data mining work you’ve been doing? I’ll be guided by you, but perhaps a co-authored piece (less than 1000 words) about the project as a case study for how tech can benefit science/conservation might be interesting."

This should be an overview of ContentMine and a combination of [Ross's intro](http://contentmine.org/2015/09/daily-updates-on-iucn-red-list-species/) post and Mark's update blog after the [current sprint](https://github.com/ContentMine/canary/milestones/IUCn%20redlist)

**Comment by jcmolloy** [comment]
@rossmounce how is this going? Can any of us help? Realise you've had a lot on with the new job :)

**Comment by jcmolloy** [comment]
@rossmounce we just had an email asking about this - would you prefer to reassign to me? I can probably carve out an hour or two this weekend but if you're on it that's great. There'n no massive rush they would just like an idea of the timeframe. Thanks!

**Comment by rossmounce** [comment]
@jcmolloy Hi Jenny, sorry I don't pay much attention to my github alerts.

I think I better not be associated with this as I'm working with IUCN on my 'day' job. We should chat about what IUCN have to offer though perhaps and how their new API could be integrated into this?

**Comment by jcmolloy** [comment]
OK! It's basically to draw attention to http://iucn.contentmine.org/. I can
throw something together so will reassign to myself!

**Comment by jcmolloy** [comment]
Completed and submitted https://docs.google.com/document/d/1qhWiAclW5LkjsVZ3FZceuP_ISmz-ljUkKjrC8APpSI4/edit?usp=drive_web
