### ISSUE TITLE
Vivienne induction

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/site#312]
- [x] Agree role description
- [x] Induction meeting with Vivienne and Jenny
- [x] Induction meeting with Vivienne and Karien
- [x] Add to Slack
- [x] Set up ContentMine email address
- [x] Add to relevant mail forwarders
- [x] Set up github account and assign relevant permissions
- [ ] Set up website account and assign relevant permissions

**Comment by jcmolloy** [comment]
@GrahamSteel are you able to add an account for Vivienne on the WP site? If not, could you reassign to Stefan? Thanks!

**Comment by GrahamSteel** [comment]
Don't have WP rights to do this

**Comment by jcmolloy** [comment]
OK - I've reassigned to Stefan.

**Comment by viviennelm** [comment]
All done.
