### ISSUE TITLE
work out policy strategy

### ISSUE THREAD

**Issue by skasberger** [ContentMine/site#324]
regarding EU commission lobbying:
- what do we want to do?
- who does it?

**Comment by jcmolloy** [comment]
@petermr @rossmounce @Blahah @GrahamSteel we have this week only to do something. I have posted the advocacy case studies to the website as a draft which @GrahamSteel will publish tomorrow and suggest we work hard to get people to contribute on Twitter their own uses of text mining and any problems they've had like ChrisH. I can send these to all of our advocacy contacts. I don't have time to do anything around letter writing. Are we going to do something?

**Comment by petermr** [comment]
I was planning to write to East Of England MEPs today using WriteToThem and asking them to write to OEttinger supporting the Reda reforms. I'd publicize the letter and this can act as a format that others could use. Our information is that multiple signatories to a letter only count as one, and that it's more beneficial for several individuals to write individual letters. I think sending the MEPs the case studies and making them public, is probably the most cost-effective way to proceed.

**Comment by blahah** [comment]
Yes, let's do this. We should write to all UK MEPs, and to contacts at UK universities around the country, asking them to contact their MEPs. I agree that we should provide a template letter that links to a body of evidence.

I can put some time into writing the letter towards the middle of the week.

**Comment by jcmolloy** [comment]
Here is the link to Chris Hartgerink's letter which could act as a starting
point
https://docs.google.com/document/d/1YiMpdcWrZNl8Y3Pyls67OuBySAZEdLHuBylh38Urc58/edit

**Comment by petermr** [comment]
Have opened a GDoc: https://docs.google.com/document/d/1l4AwNhBcpBmiMbkspDWuRZAeH_ifKGVRU-Fzq9714q0/edit#

**Comment by petermr** [comment]
We may have more than one document - it can be a good idea to send several letters to MEPs as long as the wording is significantly different.  I am writing this with a Cambridge perspective as I think that personalises it.

**Comment by jcmolloy** [comment]
I sent to the Cambridge MEPs. Now should probably wait until it comes to the parliament and revisit in the lead up to that vote. Will keep informed with advice from LIBER!
