### ISSUE TITLE
Add advocacy case studies to website

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/site#327]

**Comment by viviennelm** [comment]
Is this the same action as the one for you to tidy up Chris' case study document?  Don't want to duplicate it if it is!

**Comment by jcmolloy** [comment]
@viviennelm - it's related but different :)
@skasberger I can't resize images in posts so can't recreate the document format. I'm just using plain HTML and they're always at 100% width - any ideas?

**Comment by GrahamSteel** [comment]
add the next line
style="width:auto;"
to your image html code
this overwrites the 100% value.

**Comment by jcmolloy** [comment]
:+1:  Thanks @GrahamSteel ! I can write style="width:whatwidtheveriwant;". Fixed @stefankasberger (and I'm sure you have this documented somewhere, I admittedly didn't look :)

**Comment by jcmolloy** [comment]
@GrahamSteel I'm assigning this to you so you can push out the post at a more social media friendly time on Monday and set up some tweets. Thanks very much! [Post Draft Link](http://contentmine.org/wp-admin/post.php?post=1357)

**Comment by GrahamSteel** [comment]
Thanks. Will do.

**Comment by jcmolloy** [comment]
@viviennelm I just realised what you were asking - no need to post that action, I did it  just now! Thanks!

**Comment by GrahamSteel** [comment]
@jcmolloy I'll push this out at 13:00 tomorrow.

**Comment by GrahamSteel** [comment]
@jcmolloy, do you want me to put out a tweet either tonight or tomorrow morning along the lines of "Watch out for an important @thecontentmine blogpost at 13:00" ?

**Comment by jcmolloy** [comment]
No need for that, just make sure it gets tweeted a good few times when it is out :)
