### ISSUE TITLE
GENERAL ACTION - watch advocacy panel from OpenCon

### ISSUE THREAD

**Issue by viviennelm** [ContentMine/site#332]
Recommended action from team meeting on 25/11/15 - gives a good overview on the views regarding copyright reform in Brussels at present.

**Comment by GrahamSteel** [comment]
Video at https://youtu.be/oSX_yrh0SVs

**Comment by jcmolloy** [comment]
Assuming most people who want to have now done this so closing issue @GrahamSteel @chreman @skasberger @viviennelm @anusharanganathan @markmacgillivray
