### ISSUE TITLE
Find registered office in Cambridge

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/site#335]
Contacted:
- [Future Business Centre](http://futurebusinesscentre.co.uk/about-the-centre/workspace/virtual-offices) to check about registered address service. Standard service is £35 a month inc free meeting room time.
- [Milton Hall](http://www.miltonhallcambridge.com/virtual-offices/) to check prices.

[St Johns Innovation Centre](http://stjohns.co.uk/accomodation/rent-address-star-service/) is also an option at £9+VAT per week for mail handling. Open Knowledge is registered here.

@petermr do you have a preference?

It would also be possible to appoint accountants who would allow us to use their address, coming recommended are:
- [Websters](http://www.tax.uk.com/)
- [Prentis & Co](http://www.prentis.co.uk/services/business/business-support.htm)

**Comment by viviennelm** [comment]
This now includes a telephone service so just need to update paperwork and can then close this issue.

**Comment by jcmolloy** [comment]
Now completed
