### ISSUE TITLE
Proposal for Open Science Prize

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/site#336]

**Comment by jcmolloy** [comment]
[Document](https://docs.google.com/document/d/17ycfS_je-CtXSRdGmkji2IVIQR-Rx5Fuy99fS9AmX5U/edit) started

**Comment by blahah** [comment]
Btw, Titus Brown's group had a visit from the Hypothes.is team and they were talking about applying for the OSP with a simple browser extension that does in-browser mining of things like DB identifiers, and links out to the resources via hypothes.is annotations.

I pointed out to them that ContentMine has similar ideas, and that perhaps collaboration would be fruitful. If CM are interested in exploring this as a possibility, let me know and I'll make the connection.

**Comment by jcmolloy** [comment]
I think that would be great - I already added them in the doc as potential
people to approach for collaboration.
@petermr - where did you leave conversations with Dan about working
together?

**Comment by blahah** [comment]
I actually meant Titus Brown's group as the collaborators - they are the Data Intensive Biology group at UC Davis :)

**Comment by jcmolloy** [comment]
Aha - I misinterpreted your 'they were talking about' - thought you meant
the Hypothes.is visitors! A connection to Titus Brown's group would be
great, thanks very much!

Jenny

**Comment by blahah** [comment]
Hey @ctb, interested in exploring that idea for annotating papers in-browser with Hypothes.is?

**Comment by jcmolloy** [comment]
Our idea was that we'd create a bunch of scrapers and API connectors to
process as many biomedical journal articles as we can through the
ContentMine normalisation pipeline. Then extract all of the DB IDs we can
make regular expressions for from the [list of data sources](https://docs.google.com/spreadsheets/d/14_oCSKXcDWlcc4UBjLEh2KFidYN7ZBfCMNbz2iXu-2M/edit#gid=1595396026) provided by the Open Science Prize + any others we come up with. The fact
that certain identifiers are mentioned in certain papers would then be
released as open data (including from closed access full text, because
facts are not copyrightable and we're in the UK so we can mine closed
access for non-commercial purposes). This dataset could make for some
useful cross-linking. In terms of annotation, we've generically talked to
Hypothes.is about turning our facts into annotations so we know it should
be possible. We're more than open to any sort of collaboration :)

**Comment by markmacgillivray** [comment]
Just a reminder, we can already add annotations into OA articles. The facts index can be used as a backend for the annotator, which can add highlights onto the html document.

**Comment by blahah** [comment]
So (if I remember correctly) @ctb was talking about having a simple JS thing in the browser that would use a library of regexes to annotate entities on the page as the user visited it, and submit them to hypothes.is if they weren't already there. Then it wouldn't matter whether it was open or closed, and once annotated and added to hypothes.is anyone would be able to view the facts in-page.

We could link it up with the CM facts index so those things were submitted to us as well as hypothes.is. Conversely, any facts from CM could be added as hypothes.is annotations.

A further linkup could be that the annotator plugin could display the annotations with nice contexual info - something like hovering over a protein identifier would show an infobox with data about that protein.

**Comment by ctb** [comment]
Well, no one responded to my e-mail to our lab mailing list so I started talking about it with @judell. Do we want to discuss it here, or via e-mail? I'm OK with either.

**Comment by jcmolloy** [comment]
@ctb @judell discussing it here would be good - what are your thoughts on the ideas above and would you be interested to work with us to put an entry in by 29 Feb? I'm not sure if hypothes.is already have plans, but as @markmacgillivray says we can already annotate using the content mined facts and a browser plugin of the type Richard describes sounds like an excellent complement. Particularly as we were planning to write the regexes anyay.

**Comment by ctb** [comment]
On Sun, Dec 20, 2015 at 09:23:59AM -0800, Jenny Molloy wrote:

> @ctb @judell discussing it here would be good - what are your thoughts on the ideas above and would you be interested to work with us to put an entry in by 29 Feb? I'm not sure if hypothes.is already have plans, but as @markmacgillivray says we can already annotate using the content mined facts and a browser plugin of the type Richard describes sounds like an excellent complement. Particularly as we were planning to write the regexes anyay.

@jcmolloy I have a meeting with @judell and others on Jan 4th to discuss;
we're on holiday break until then :).  I will return to this issue after
Jan 4 - in the meantime, Happy Holidays & best wishes for a happy New Year!

**Comment by jcmolloy** [comment]
Thanks @ctb - have a lovely Christmas and we look forward to returning to
this in the New Year!

**Comment by jcmolloy** [comment]
@ctb @judell just to reassure we haven't forgotten about this - we're in touch with Maryann and she said you're working through some ideas so just ping us when it would be useful to join the conversation again. We're still keen!

**Comment by judell** [comment]
OK, thanks Jenny!

Jon

**Comment by jcmolloy** [comment]
Completed, published via RIO and we're through to the short-list - woohoo! http://rio.pensoft.net/articles.php?id=8424
