### ISSUE TITLE
Additional mail forwarders

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/site#337]
It would be great to have a more nuanced system so only the necessary people get copied into external emails, as discussed at weekly call. Could you set up:
operations@contentmine.org: PMR, JM, VLM (+ MM if wanted for company things)
software@contentmine.org: PMR, JM, MM, AR, RSU, SK, CK
training@contentmine.org: PMR, JM, SK, CK 

Any comments welcome from others, I will raise this at the weekly meeting so no rush!

**Comment by markmacgillivray** [comment]
Really? There are only eight people in this team. Why not just email the
relevant people? For example not all software discussions are relevant to
everyone; some training discussions are relevant to more people; over time
what people work on may change, and they may get inadvertently left out of
certain discussions. At the last meeting my preference was not to have more
forwarders - already the ones we have sometimes cause confusion when people
expect to be on a forwarder but are not.

**Comment by jcmolloy** [comment]
We only have two forwarders afaik (all@ and contact@, the latter I'm not sure who is on it, at one stage it was PMR, JM and GS) and the rest of the time people are randomly copied into conversations. The point of the forwarders is to allow roles to change without external people having to reset their contacts - we can put training@ on the training marketing material which is about to get sent out. operations@ likewise for things like expenses, Shuttleworth business and company-related correspondence. software@ probably right now isn't necessary, you're right.

**Comment by markmacgillivray** [comment]
OK, yes for external contact these make sense, like the all@ and contact@

**Comment by jcmolloy** [comment]
Relevant forwarders now added
