### ISSUE TITLE
Wireframes for funder demos

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/site#350]

**Comment by jcmolloy** [comment]
Thanks @chreman for offering to help with this - also @tarrow will hopefully be able to indicate what is feasible! I suggest we have two use cases:
1. Conservation information on species
2. Biomedical papers. Probably not Zika virus as there aren't enough of them. We have a use case of Ellie in Cambridge who is interested in diet and obesity which could be a good place to start. Could pick out a lot of genes and potentially chemicals in such papers!

**Comment by blahah** [comment]
@jcmolloy one issue with doing the biomed literature is that this is exactly what europePMC does - they have pre-mined species, genes, proteins and other chemicals and identifiers, and it's pretty easy to find and use them. Would this be doing something more? E.g. the closed-access lit?

**Comment by petermr** [comment]
Epmc is not in a very usable state for further analysis and we could can do that and of course we ca do closed

**Comment by jcmolloy** [comment]
No longer a priority - closing issue
