### ISSUE TITLE
1-2 potential use cases for facts from the API

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/site#357]
Aim to document 1-2 potential use cases for facts we will get from the API + visualisations

**Comment by jcmolloy** [comment]
@chreman we have an idea from @rossmounce 
An interesting use case for the daily-scrape stream would be to notify users/readers of 'nomenclatural acts'

Most of these acts are ‘original descriptions’ of new scientific names, but other acts may include emendations, lectotypifications et cetera.

Words/strings to look out for:

comb. nov. e.g. http://mycokeys.pensoft.net/articles.php?id=1187
sp. nov. e.g. http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0149727 
lectotype/lectotypification e.g. http://phytokeys.pensoft.net/articles.php?id=5080
emendation/emended (a formal correction) 

Also look out for
family nov.
genus nov. / gen. nov.
subsp. nov.

Why? Groups like Plazi are doing detailed mining but only of a small set journals. It would be nice perhaps for CM to help filter PLOS and the wide scatter of other journals. Plazi could then take signals from CM and do a deeper-taxonomy specific mining of articles flagged by CM

New species are pretty cool things to flag anyway, right? Interesting in of themselves

It's also particularly interesting when nomenclatural acts are buried deep within papers that are largely about something else (not easily flagged/found).

**Comment by chreman** [comment]
please see https://github.com/ContentMine/visualizations/milestone/1 for progress

**Comment by jcmolloy** [comment]
Great @chreman - look forward to seeing where you get to. The graphic design booklets are being finalised now and I think combined with a couple of visualisations they will really strengthen our case to funders :)

**Comment by jcmolloy** [comment]
Now have visualisation demos via @chreman but API deprioritised.
