### ISSUE TITLE
Email not sending from Discourse

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/site#360]
Need to check SparkPost settings etc.
@skasberger I will take a look and may defer to you, but will try my best not to distract you from exams!

**Comment by jcmolloy** [comment]
@stefankasberger: the error messages are 550 5.7.1 Unconfigured Sending Domain <contentmine.org>

So looks like Discourse is still trying to send from contentmine.org not sparkmail.contentmine.org

I've invited you to the SparkPost account

Dunno if we tried all these steps before https://support.sparkpost.com/customer/en/portal/articles/2340644-using-sparkpost-with-discourse?b_id=7411

**Comment by jcmolloy** [comment]
@skasberger any joy with this?

**Comment by jcmolloy** [comment]
@skasberger where are we with this - 👍 or 👎 !

**Comment by skasberger** [comment]
i was not able to fix it the first time. second try would mean to create a new domain at sparkpost, something we would have to do together. i am flexible in the next weeks.

**Comment by jcmolloy** [comment]
Checked other Discourse instance and working fine with sendinblue, might be worth trying that provider

**Comment by jcmolloy** [comment]
Now fixed - result of 'send from' email address not matching sending domain.
