### ISSUE TITLE
Fellows on-boarding

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/site#361]
Getting six Fellows into ContentMine communications channels and setting up the calendar for training and calls.
- [x]  Plan training [SK]
- [x] Add to Slack [JM]
- [x] Add to Github organisation [TA]
- [x] Add to WordPress blog [GS]
- [x] Post Fellows welcome blog [SK]
- [x] Set up calendar for check-ins [SK]
- [x] ContentMine stash + AMI [SK+TA]

**Comment by jcmolloy** [comment]
@tarrow I have added you because none of the rest of us are owners of the github organisation. Could you add all the fellows to a team? I'm not sure what all of their github user IDs are but hopefully you can find them easily! (list of names is in the welcome email)

**Comment by GrahamSteel** [comment]
WordPress invitations sent.

**Comment by jcmolloy** [comment]
Thanks @GrahamSteel

**Comment by jcmolloy** [comment]
Notes for @skasberger on Fellows on-boarding, let me know here if you have any further questions!

**What are the requirements regarding intro blog post and fellows pages?**
I suggest we have a page on the website that lists the Fellows with:
- Name and affiliation
- Photo
- links to their social media accounts
- one sentence about their project
- Link to their blog post and where they will document their project.

On the blog, everyone should have an introductory post and they have sent their text for that plus photo. I will quickly draft a congratulatory note now if you like which can be joint from the CM team.

**Reporting frequency**

As per the Fellows advert, they should post a monthly blog post and a final report as a blog post

**Fortnightly calls**

The fellowship is for 6 months, the fortnightly calls will be for around one hour and offer:
Support for each other and from the CM team
- Chance to feedback on software 
- Opportunity to request and deliver mini skills sessions and software tutorials
  The calls should have 1-2 people from ContentMine and one of those should be a dev. Most likely SK/TA or SK/PMR or TA/PMR would be the most likely combinations. I can also take them as necessary.
  There are no plans for additional longer induction sessions except the one-off at the start of the fellowship.

**Fellow communications**
Fellows will not have a CM email address, but if they are happy we could include their own email address on the website page (probably better to link to their departmental website or just social media). We should mostly contact them via the #fellows channel and we should make sure they are all on Discourse but there is no need for another mailing list for them.

**Will there be a homework between calls?**
Not by default - they should all be getting on with their project and the calls are for support and help, but if they ask for a specific tutorial or training then it might be helpful to have optional homework for those that are interested. Before the induction session, there might be a need for them to try something. They have already completed [an exercise](https://docs.google.com/document/d/1pnv_FPTBEfVffHS-gE9pY5lp9LfkhGKr_GNUWjnJZXY/edit) as part of the application process so have the sw installed and have used it. This is the 'instructions to applicants; you referenced.

**What is the cover letter for? is this the description for the fellows webpage?**
Yes - this will make up their blog post. You could give them access to the post to check over and then post under their own name, in case they want to add something.

**Fellows descriptions and text/Markdown/HTML**
I asked them to send it as text, so I think it would be a bit unfair to now ask them to do it as Markdown. Most don't have much formatting so it shouldn't take too long to copy into WordPress - sorry for producing more work, I am happy to help with the reformatting if it ends up taking a while.

**Comment by jcmolloy** [comment]
Text from [the advert ](https://contentmining.wordpress.com/2016/04/27/announcing-contentmine-fellowships/)is quite useful for spelling out what we offered and what we expect:

**What ContentMine Fellows can expect from us:**
- £1000 and some ContentMine merchandise!
- A one-day webinar workshop to help you get started with the software.
- Fortnightly support calls with the ContentMine developers.
- Access to support via ContentMine Slack (chat app).
- Priority support and bug fixes to help keep your research up and running.
- Excitement and enthusiasm for your project! We are researchers and we love science.

**What we expect from ContentMine Fellows:**
- We promote open notebook science! You will record your progress via github and the ContentMine discussion forum.
- Three blog posts summarising progress over the course of six months, one of which will be the final report.
- Willingness to explore new methods of research and research communication.
- Attendance at fortnightly calls with members of the ContentMine team to help each other and discuss bugs or features for the software.
- Detailed bug reporting and feedback on our software.

**Comment by jcmolloy** [comment]
@tarrow could you add the fellows to the github organisation or maybe boost @skasberger to also be an owner and then he can do it? Thanks!

**Comment by jcmolloy** [comment]
@tarrow any progress on adding the fellows to github team so we can look to close this issue? The new logo is now available (only in .ai format for time being), which means we can get stickers ordered and any other stash/AMIs distributed but I will raise a separate issue for that.

**Comment by jcmolloy** [comment]
@tarrow will make @skasberger an owner

**Comment by jcmolloy** [comment]
Will add CM stash to another issue
