### ISSUE TITLE
ContentMine Stickers

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/site#362]
@tarrow thanks for offering the other week to think about stash :+1: 

Do you think hexagonal/tesselating shapes would be better or a custom die cut?
I have heard good things about StickerMule https://www.stickermule.com/uk/custom-stickers

**Comment by tarrow** [comment]
I think hexagonal would be pretty cool. I too have heard good things about sticker mule. Do we have high quality or vector files from the GFX guy? Looks like it is £36 for 50 or £42 for 100

**Comment by blahah** [comment]
+1 for hex stickers. Stickermule is the standard for getting them made - vinyl matte is the nicest finish imo. There's also https://hexi.pics/help_en which specialises in hex stickers and ships worldwide.

Here's the spec for hex stickers: https://github.com/terinjokes/StickerConstructorSpec

**Comment by jcmolloy** [comment]
We will have vector files - I will get these this week

**Comment by jcmolloy** [comment]
Here are the [ai files](https://drive.google.com/drive/u/0/folders/0B9V3tIqIu0UZQnRBblVOZVlXczQ) (a little later than anticipated!) and I will make into sticker artwork unless someone else would like to! @tarrow are you still planning some laser cut gifts for the Fellows?
Need to convert to svg on a computer with AI - hopefully this week.

**Comment by jcmolloy** [comment]
Stickers order - expected 17 Oct
